package openscanner.cc;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.MultiMap;
import io.vertx.core.http.HttpServer;
import io.vertx.ext.web.Router;
import openscanner.cc.utils.Property;

import java.util.Properties;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sunc' at '16-5-24 上午10:16' with Gradle 2.9
 *
 * @author sunc, @date 16-5-24 上午10:16
 */
public class Home extends AbstractVerticle {

    @Override
    public void start() {
        HttpServer server = vertx.createHttpServer();

        Router router = Router.router(vertx);

        router.route("/").handler(ctx -> {
            ctx.response().setChunked(true);
            try {
//                FileInputStream input = new FileInputStream("conf/https.properties");
                Properties pro = get();
//                pro.load(input);
                for(String key:pro.stringPropertyNames())
                    ctx.response().write(key + ":" + pro.get(key) + "\n");
            } catch (Exception e) {
                e.printStackTrace();
            }
            MultiMap map = ctx.request().headers();
            ctx.response().write("********************\n");
            for (String key : map.names())
                ctx.response().write(key + ":" + map.get(key) + "\n");
            ctx.response().end();

        });

        server.requestHandler(router::accept).listen(8090, "localhost", res -> {
            if (res.succeeded())
                System.out.println("success");
        });
    }

    public static Properties get(){
        return new Property().getProperties("conf/https.properties");
    }

}
